//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Book_Code { get; set; }
        public string Book_Class { get; set; }
        public Nullable<System.DateTime> Book_PurchaseTime { get; set; }
        public string Book_Name { get; set; }
        public string Book_Author { get; set; }
        public string Book_Publisher { get; set; }
        public string Book_Introduction { get; set; }
        public string Book_Status { get; set; }
        public Nullable<int> Member_Code { get; set; }
        public string Member_Name { get; set; }
    }
}
